# Generated by Django 4.1 on 2023-11-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='ordermodel',
        ),
    ]
