# Generated by Django 4.1 on 2023-11-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_order_orderitem_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordermodel',
            new_name='order',
        ),
    ]
